PresentationLayer/ViewModels/AllocationViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace PresentationLayer.ViewModels;

public class AllocationViewModel
{
    public int AllocationId { get; set; }
    public int ProjectId { get; set; }
    public string ProjectName { get; set; }
    public int EmployeeId { get; set; }
    public string EmployeeName { get; set; }
    public int AllocationPercentage { get; set; }
    public DateTime StartDate { get; set; }
    public DateTime? EndDate { get; set; }
    public int? LevelId { get; set; }
    public string LevelName { get; set; }
    public int? PositionId { get; set; }
    public string PositionName { get; set; }
    public IEnumerable<SelectListItem> Levels { get; set; }
    public IEnumerable<SelectListItem> Positions { get; set; }
    public IEnumerable<SelectListItem> Projects { get; set; }
}

PresentationLayer/Controllers/AllocationController.cs
using AutoMapper;
using BusinessLayer.DTOs;
using BusinessLayer.Interfaces;
using DataLayer.Enums;
using FluentValidation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PresentationLayer.ViewModels;
using System.Linq.Dynamic.Core;



namespace PresentationLayer.Controllers;
[Authorize(Roles = "Project Delivery Manager")]
public class AllocationController : Controller
{
    private readonly IAllocationService _allocationService;
    private readonly IMapper _mapper;
    private readonly ILookUpService _lookUpService;
    private readonly IProjectService _projectService;
    private readonly IEmployeeService _employeeService;

    public AllocationController(IAllocationService allocationService, IMapper mapper, ILookUpService lookUpService, IProjectService projectService, IEmployeeService employeeService)
    {
        _allocationService = allocationService;
        _mapper = mapper;
        _lookUpService = lookUpService;
        _projectService = projectService;
        _employeeService = employeeService;
    }

    [HttpGet]
    [Authorize(Roles = "Project Delivery Manager")]
    public IActionResult Index()
    {
        return View();
    }
    [HttpPost]
    [Authorize(Roles = "Project Delivery Manager")]
    public async Task<IActionResult> GetAllAlocation()
    {
        var draw = int.Parse(Request.Form["draw"].FirstOrDefault() ?? "0");
        var start = int.Parse(Request.Form["start"].FirstOrDefault() ?? "0");
        var length = int.Parse(Request.Form["length"].FirstOrDefault() ?? "0");
        var sortColumn = Request.Form[string.Concat("columns[", Request.Form["order[0][column]"], "][name]")].FirstOrDefault() ?? "0";
        var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault() ?? "0";
        var searchValue = Request.Form["search[value]"].FirstOrDefault() ?? "0";

        var (allocations, totalRecords) = await _allocationService.GetAllocationTableAsync(start, length, searchValue, sortColumn, sortColumnDirection);

        var jsonData = new
        {
            draw = draw,
            recordsTotal = totalRecords,
            recordsFiltered = totalRecords,
            data = allocations
        };

        return Ok(jsonData);
    }

    [HttpGet]
    [Authorize(Roles = "Project Delivery Manager")]
    public async Task<IActionResult> Create()
    {
        var viewModel = new CreateAllocationViewModel
        {
            Employees = await GetEmployeesAsync(null, null, null, null),
            Projects = await GetProjectsAsync(),
        };
        await PopulateDropdownLists(viewModel);

        return View(viewModel);
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = "Project Delivery Manager")]
    public async Task<IActionResult> Create(CreateAllocationViewModel viewModel)
    {

        if (!ModelState.IsValid)
        {
            viewModel.Employees = await GetEmployeesAsync(viewModel.LevelId, viewModel.PositionId, viewModel.AllocationPercentage, viewModel.ProjectId);
            viewModel.Projects = await GetProjectsAsync();
            await PopulateDropdownLists(viewModel);
            return View(viewModel);
        }
        var project = await _projectService.GetProjectByIdAsync(viewModel.ProjectId);
        if (project.EndDate <= viewModel.EndDate)
        {
            ModelState.AddModelError(nameof(viewModel.EndDate), $"The EndDate must be less than or equal EndDate of Project (Project ends on {project.EndDate.ToString()})");
        }
        if (project.StartDate > viewModel.StartDate)
        {
            ModelState.AddModelError(nameof(viewModel.StartDate), $"The StartDate must be greater than or equal startDate of Project (Project starts on {project.StartDate.ToString()})");
        }
        if (ModelState.ErrorCount > 0)
        {
            viewModel.Employees = await GetEmployeesAsync(viewModel.LevelId, viewModel.PositionId, viewModel.AllocationPercentage, viewModel.ProjectId);
            viewModel.Projects = await GetProjectsAsync();
            await PopulateDropdownLists(viewModel);
            return View(viewModel);
        }
        var allocationDto = _mapper.Map<AddAllocationDto>(viewModel);
        try
        {
            await _allocationService.CreateAllocationAsync(allocationDto);
            TempData["SuccessCreate"] = "Allocation created successfully!";
            return RedirectToAction("Create");
        }
        catch (ValidationException ex)
        {
            foreach (var error in ex.Errors)
            {
                ModelState.AddModelError("", error.ErrorMessage);
            }
            viewModel.Employees = await GetEmployeesAsync(viewModel.LevelId, viewModel.PositionId, viewModel.AllocationPercentage, viewModel.ProjectId);
            viewModel.Projects = await GetProjectsAsync();
            await PopulateDropdownLists(viewModel);
            return View(viewModel);
        }
    }


    [HttpGet]
    public async Task<IActionResult> Edit(int id)
    {
        var allocation = await _allocationService.GetAllocationByIdAsync(id);
        if (allocation == null)
        {
            return NotFound();
        }
        var viewModel = _mapper.Map<EditAllocationViewModel>(allocation);
        viewModel.Projects = await GetFilteredProjectAsync(viewModel.EmployeeId, viewModel.AllocationId);


        return View(viewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(EditAllocationViewModel viewModel)
    {
        if (!ModelState.IsValid)
        {
            viewModel.Projects = await GetFilteredProjectAsync(viewModel.EmployeeId, viewModel.AllocationId);

            return View(viewModel);
        }
        var project = await _projectService.GetProjectByIdAsync(viewModel.projectId);
        if (project.EndDate <= viewModel.EndDate)
        {
            ModelState.AddModelError(nameof(viewModel.EndDate), $"The EndDate must be less than or equal EndDate of Project (Project ends on {project.EndDate.ToString()})");
        }
        if (project.StartDate >= viewModel.StartDate)
        {
            ModelState.AddModelError(nameof(viewModel.StartDate), $"The StartDate must be greater than or equal startDate of Project (Project Starts on {project.StartDate.ToString()})");
        }
        if (ModelState.ErrorCount > 0)
        {
            viewModel.Projects = await GetFilteredProjectAsync(viewModel.EmployeeId, viewModel.AllocationId);
            return View(viewModel);
        }
        var allocationDto = _mapper.Map<EditAllocationDto>(viewModel);

        try
        {
            await _allocationService.EditAllocationAsync(allocationDto);
            TempData["editSuccess"] = "Edit allocation Done Successfully";
            return RedirectToAction("Edit");
        }
        catch (ValidationException ex)
        {
            foreach (var error in ex.Errors)
            {
                ModelState.AddModelError("", error.ErrorMessage);
            }
            viewModel.Projects = await GetFilteredProjectAsync(viewModel.EmployeeId, viewModel.AllocationId);
            return View(viewModel);
        }
    }


    private async Task<IEnumerable<SelectListItem>> GetFilteredProjectAsync(int? employeeId, int? aloocationId)
    {
        var projects = await _allocationService.GetFilteredProjectsAsync(employeeId.GetValueOrDefault(), aloocationId.GetValueOrDefault());
        return projects.Select(e => new SelectListItem
        {
            Value = e.ProjectId.ToString(),
            Text = e.Name
        }).ToList();
    }


    [HttpPost]
    [Authorize(Roles = "Project Delivery Manager")]
    public async Task<IActionResult> SoftDelete(int id)
    {
        var resualt = await _allocationService.SoftDeleteAllocationAsync(id);
        if (!resualt)
        {
            return NotFound();
        }
        TempData["SuccessDeleteAlloc"] = "Allocation deleted successfully!";
        return RedirectToAction("Index");
    }


    private async Task<IEnumerable<SelectListItem>> GetEmployeesAsync(int? levelId, int? positionId, int? allocationPercentage, int? projectId)
    {

        var employees = await _allocationService.GetEmployeesForAllocationAsync(levelId.GetValueOrDefault(), positionId.GetValueOrDefault(), allocationPercentage.GetValueOrDefault(), projectId.GetValueOrDefault());
        return employees.Select(e => new SelectListItem
        {
            Value = e.EmployeeId.ToString(),
            Text = e.EmployeeName
        }).ToList();
    }

    private async Task<IEnumerable<SelectListItem>> GetProjectsAsync()
    {
        // Fetch projects from the service and map them to SelectListItem
        var projects = await _projectService.GetAllProjectsAsync();
        return projects.Select(p => new SelectListItem
        {
            Value = p.ProjectId.ToString(),
            Text = p.Name
        }).ToList();
    }

    [HttpGet]
    public async Task<IActionResult> GetEmployees(int? levelId, int? positionId, int? allocationPercentage, int? projectId)
    {
        var employees = await GetEmployeesAsync(levelId, positionId, allocationPercentage, projectId);
        return PartialView("_EmployeeList", employees);
    }

    private async Task<IEnumerable<SelectListItem>> GetDropDownItems(LookUpEnums.CategoryCode category, int? selectedValue = null)
    {
        var lookUps = await _lookUpService.GetLookUpsByCategoryAsync(category);
        return new SelectList(lookUps, "LookUpId", "NameEn", selectedValue);
    }


    private async Task<CreateAllocationViewModel> PopulateDropdownLists(CreateAllocationViewModel viewModel)
    {
        viewModel.Levels = await GetDropDownItems(LookUpEnums.CategoryCode.Level, viewModel.LevelId);
        viewModel.Positions = await GetDropDownItems(LookUpEnums.CategoryCode.Position, viewModel.PositionId);

        return viewModel;
    }

    [HttpGet]

PresentationLayer/Views/Allocation/Add.cshtml
@using PresentationLayer.ViewModels
@model AllocationViewModel
<div class="container w-100 d-flex justify-content-center align-items-center" style="margin-top: 25px;">
    <div class="row h-100">
        <div class="col-12 col-md-8 col-lg-6">
            <div class="card" style="border-radius: 15px; width: 800px;">
                <div class="card-body p-5">
                    <h2 class="text-uppercase text-center mb-4">Add Allocation</h2>
                    <form>
                        <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>
                        <div class="row mb-4">
                            <div class="col-md-6 mb-3">
                                <div class="form-group">
                                    <label asp-for="LevelId" class="control-label">Levels</label>
                                    <select id="LevelDropdown" asp-for="LevelId" class="form-control" asp-items="Model.Levels">
                                        <option value="">-Select Level Of Experience-</option>
                                    </select>
                                    <span id="LevelDropdownError" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-md-6 mb-3">
                                <div class="form-group">
                                    <label asp-for="PositionId" class="control-label">Positions</label>
                                    <select id="PositionDropdown" asp-for="PositionId" class="form-control" asp-items="Model.Positions">
                                        <option value="">-Select Position-</option>
                                    </select>
                                    <span id="PositionDropdownError" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="row mb-4">
                            <div class=" col-md-6">
                                <div class="dropdown">
                                    <label class="control-label fw-bold">Employee</label>
                                    <select class="col-sm-12 col-form-label fs-5 fw-bold" disabled><option>Select Employee</option></select>
                                    <div class="dropdown-content" id="EmployeeList">
                                    </div>
                                    <span id="EmployeeListError" class="text-danger"></span>
                                </div>
                            </div>


                            <div class="col-12 col-md-6">
                                <div class="form-group">
                                    <label asp-for="ProjectId" class="control-label fw-bold">Project</label>
                                    <select asp-for="ProjectId" class="form-control" asp-items="Model.Projects"></select>
                                    <span id="ProjectIdError" class="text-danger"></span>
                                </div>
                            </div>
                        </div>

                        <div class="row mb-4">
                            <div class="col-12 col-md-6">
                                <div class="form-group">
                                    <label class="col-form-label fw-bold">Allocation Percentage</label>
                                    <input type="number" asp-for="AllocationPercentage" min="25" max="100" class="form-control" />
                                    <span id="AllocationPercentageError" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="col-12 col-md-6">
                                <div class="form-group">
                                    <label class="col-form-label fw-bold">Start Date</label>
                                    <input type="date" asp-for="StartDate" class="form-control" />
                                    <span id="StartDateError" class="text-danger"></span>
                                </div>
                            </div>
                        </div>

                        <div class="row mb-4">
                            <div class="col-12 col-md-6">
                                <div class="form-group">
                                    <label class="col-form-label fw-bold">End Date</label>
                                    <input type="date" asp-for="EndDate" class="form-control" />
                                    <span id="EndDateError" class="text-danger"></span>
                                </div>
                            </div>
                        </div>

                        <div class="form-group mb-3 text-center">
                            <input type="button" onclick="submitForm()" class="btn btn-primary btn-lg custom-button" value="Submit" />
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        attachChangeHandler('#ProjectId');
        attachChangeHandler('#LevelDropdown');
        attachChangeHandler('#EmployeeList');
        attachChangeHandler('#PositionDropdown');
        attachChangeHandler('#AllocationPercentage');
        attachChangeHandler('#StartDate');
        attachChangeHandler('#EndDate');

        $('#LevelDropdown, #PositionDropdown').change(function () {
            var levelId = $('#LevelDropdown').val();
            var positionId = $('#PositionDropdown').val();

            $.ajax({
                url: '@Url.Action("getEmployees", "Allocation")',
                type: 'GET',
                data: {
                    levelId: levelId,
                    positionId: positionId
                },

                success: function (data) {
                    var employeeDropdown = $('#EmployeeList');
                    employeeDropdown.empty();
                    // employeeDropdown.append('<option value="">-Select Employee-</option>');

                    $.each(data, function (index, item) {
                        employeeDropdown.append(`<label><input type="checkbox" name="employees" value="${item.value}">${item.text}</label>`);

                    });
                    //emloyeeDropdown.prop('disabled', data.length === 0); // Disable if no employees found
                    
                },

                error: function () {
                    alert("An error occurred while loading employees.");
                }
            });
        });
    });

    function submitForm() {
        var selectedEmployee = document.querySelectorAll('input[name="employees"]:checked');
        var employees = [];
        if(selectedEmployee.length == 0) {
            validateField('#EmployeeList', 'You should choose at least one employee.');
        }
        for (var i = 0; i < selectedEmployee.length; i++) {
            employees.push(parseInt(selectedEmployee[i].value));
        }

        let isValid = false;
        var selectedProject = $('#ProjectId').val();
        var levelIdValue = $('#LevelDropdown').val();
        var positionIdValue = $('#PositionDropdown').val();
        var allocationPercentageValue = $('#AllocationPercentage').val();
        var startDateValue = $('#StartDate').val();
        var endDateValue = $('#EndDate').val();

        isValid = validateField('#ProjectId', 'Project is required');
        isValid = validateField('#LevelDropdown', 'Level is required');
        isValid = validateField('#PositionDropdown', 'Position is required');
        isValid = validateField('#AllocationPercentage', 'Allocation percentage is required');
        isValid = validateField('#StartDate', 'Start date is required');
        isValid = validateField('#EndDate', 'End date is required');

        if (!isValid) {
            return false;
        }

        $.ajax({
            url: "/Allocation/Add",
            type: "POST",
            contentType: "application/json",
            data: JSON.stringify({
                Employees: employees,
                projectId: parseInt(selectedProject),
                LevelId: parseInt(levelIdValue),
                PositionId: parseInt(positionIdValue),
                AllocationPercentage: parseInt(allocationPercentageValue),
                StartDate: startDateValue,
                EndDate: endDateValue
            }),
            dataType: "json",
           
            success: function (response) {
                window.location = '/Allocation/Index';
            },
            error: function (xhr, status, error) {
                console.log("Error" + error);
            }
        });

    }

    function validateField(selector, errorMessage) {
        var value = $(selector).val();
        if (!value) {
            $(selector).addClass('is-invalid');
            $(selector + 'Error').text(errorMessage);
            return false;
        } else {
            $(selector).removeClass('is-invalid');
            $(selector + 'Error').text('');
            return true;
        }
    }

    function addError(selector, errorMessage) {
        $(selector).addClass('is-invalid');
        $(selector + 'Error').text(errorMessage);
    }

    function attachChangeHandler(selector) {
        $(selector).on('change input', function () {
            validateField(selector, ''); // Passing an empty message to clear the error
        });
    }
</script>

<style>
    .custom-button {
        width: 200px; /* Set your desired width */
        height: 45px; /* Set your desired height */
        font-size: 1.3rem; /* Adjust font size */
        text-align: center; /* Center text */
    }

    .card {
        margin: auto; /* Center the card */
        max-width: 800px; /* Limit card width */
        width: 100%; /* Allow card to be responsive */
    }

    .form-control {
        height: 45px; /* Keep a consistent height */
    }


    .dropdown {
        position: relative;
        display: inline-block;
    }

    .dropdown-content {
        display: none;
        position: absolute;
        background-color: #f9f9f9;
        min-width: 200px;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        z-index: 1;
    }

        .dropdown-content label {
            display: block;
            margin-top: 10px;
            margin-left: 5px;
        }

    .dropdown:hover .dropdown-content {
        display: block;
    }
</style>

PresentationLayer/Views/Allocation/AllocationHistory.cshtml
@using BusinessLayer.DTOs
@model IEnumerable<AllocationHistoryDto>
@{ 
    ViewBag.Title = "Allocation History";

}
<link href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
<link href="~/css/ProjectColor.css" rel="stylesheet" />

<div class="row mb-2 mt-5">
    <div class="col-md-12">
        <table id="historyTable" class="table table-striped table-bordered dt-responsive nowrap mb-0 align-middle" style="width:100%;">
            <thead>
                <tr>
                    <th>Employee Name</th>
                    <th>Level Name</th>
                    <th>Position Name</th>
                    <th>Project Name</th>
                    <th>Allocation %</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>

@section Scripts {
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.3"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.0.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.0.1/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.7.1/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.0.1/js/buttons.flash.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#historyTable').DataTable({
                "serverSide": true,
                "processing": true,
                "ajax": {
                    "url": "@Url.Action("AllocationHistory", "Allocation")",
                    "type": "POST",
                    "dataType": "json"
                },
                "columns": [
                    { "data": "employeeName", "name": "EmployeeName", "autoWidth": true },
                    { "data": "levelName", "name": "LevelName", "autoWidth": true },
                    { "data": "positionName", "name": "PositionName", "autoWidth": true },
                    { "data": "projectName", "name": "ProjectName", "autoWidth": true },
                    { "data": "allocationPercentage", "name": "AllocationPercentage", "autoWidth": true },
                    {
                        "data": "startDate",
                        "name": "StartDate",
                        "autoWidth": true,
                        "render": function (data) {
                            return data ? new Date(data).toLocaleDateString() : '';
                        }
                    },
                    {
                        "data": "endDate",
                        "name": "EndDate",
                        "autoWidth": true,
                        "render": function (data) {
                            return data ? new Date(data).toLocaleDateString() : '';
                        }
                    },
                ],
                "responsive": true,
                "autoWidth": false,
            });
        });
    </script>
}

PresentationLayer/Views/Allocation/Edit.cshtml
@model PresentationLayer.ViewModels.EditAllocationViewModel

@{
    ViewBag.Title = "Edit Allocation";
}
<style>
    ul {
        list-style-type: none;
        padding-left: 0;
    }
</style>

<link href="~/startbootstrap-sb-admin-2/css/sb-admin-2.min.css" rel="stylesheet" />
<link href="~/css/ProfileCSS.css" rel="stylesheet" />
<link href="~/css/ProjectColor.css" rel="stylesheet" />
<div class="container-fluid mt-4">
    <div class="row justify-content-center">
        <div class="col-lg-10 col-md-10">
            <div class="card  mb-4">
                <div class="card-body p-5">
                            <h2 class="text-capitalize text-center mt-5 mb-3">Edit Allocation</h2>

                            <form asp-action="Edit" method="post">
                                <input type="hidden" asp-for="AllocationId" />
                                <input type="hidden" asp-for="EmployeeId" />
                                <input type="hidden" asp-for="LevelId" />
                                <input type="hidden" asp-for="PositionId" />
                                <div class="row">

                                    <div asp-validation-summary="ModelOnly" class="text-danger mb-3 col-12"></div>

                                    <div class="col-12 col-md-6">
                                        <div class="form-group">
                                            <label asp-for="projectId" class="control-label">Project:</label>
                                            <select asp-for="projectId" class="form-control" asp-items="Model.Projects"></select>
                                            <span asp-validation-for="projectId" class="text-danger"></span>
                                        </div>
                                    </div>

                                    <div class="col-12 col-md-6">
                                        <div class="form-group">
                                            <div class="form-horizontal">
                                                <label asp-for="AllocationPercentage">Allocation Percentage:</label>
                                                <select asp-for="AllocationPercentage" class="form-control" id="percentage-dropdown">
                                                    <option value="25">25%</option>
                                                    <option value="50">50%</option>
                                                    <option value="75">75%</option>
                                                    <option value="100">100%</option>
                                                </select>
                                                <span asp-validation-for="AllocationPercentage" class="text-danger"></span>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-12 col-md-6">
                                        <div class="form-group">
                                            <label asp-for="StartDate" class="control-label">Start Date:</label>
                                            <input asp-for="StartDate" class="form-control" type="date" />
                                            <span asp-validation-for="StartDate" class="text-danger"></span>
                                        </div>
                                    </div>

                                    <div class="col-12 col-md-6">
                                        <div class="form-group">
                                            <label asp-for="EndDate" class="control-label">End Date:</label>
                                            <input asp-for="EndDate" class="form-control" type="date" />
                                            <span asp-validation-for="EndDate" class="text-danger"></span>
                                        </div>
                                    </div>



                                    <div class="col-12">
                                        <div class="form-group text-center mt-5">
                                            <input type="submit" value="Save Changes" class="btn btn-primary" />
                                            <a asp-controller="Allocation" asp-action="Index" class="btn btn-secondary">Cancel</a>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
 

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

@if (TempData["editSuccess"] != null)
    {
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script>
        Swal.fire({
            icon: 'success',
            title: 'Success!',
            text: '@TempData["editSuccess"]',
            timer: 2000,
            timerProgressBar: true,
            showConfirmButton: false
        }).then((result) => {
                         window.location.href = '@Url.Action("Index", "Allocation")';
        });
    </script>
    }

PresentationLayer/Views/Allocation/_EmployeeList.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "Employee List";

}

@model IEnumerable<SelectListItem>

@foreach (var employee in Model)
{
    <div class="form-check">
        <input class="form-check-input" type="checkbox" name="SelectedEmployeeIds" value="@employee.Value" id="employee-@employee.Value" />
        <label class="form-check-label" for="employee-@employee.Value">
            @employee.Text
        </label>
    </div>
}